CREATE TABLE students (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    description VARCHAR(1000)
);

CREATE TABLE student_courses (
    student_id BIGINT NOT NULL,
    course_id BIGINT NOT NULL,

    PRIMARY KEY (student_id, course_id),

    CONSTRAINT fk_student_courses_student
        FOREIGN KEY (student_id)
        REFERENCES students(id),

    CONSTRAINT fk_student_courses_course
        FOREIGN KEY (course_id)
        REFERENCES courses(id)
);